### ISSUE TITLE
Update readme for connect to local remotedev server on Android

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remotedev-server#1]
On Android, we should use 10.0.2.2 (Genymotion: 10.0.3.2) instead of localhost.

**Comment by zalmoxisus** [comment]
An pr with this additional info to https://github.com/zalmoxisus/remotedev-server#connect-from-android-device-or-emulator would be welcome, though I think it's better to use the same host for ios and android, and just point it with `adb` (of course only when developing for both platform).
