### ISSUE TITLE
[Proposal] Injecting to React Native local server

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remotedev-server#12]
Just a same feature with `--injectserver` option of [remotedev-on-debugger](https://github.com/jhen0409/remote-redux-devtools-on-debugger#options---option), maybe call it `--inject-rnserver` (desktop: `--inject-rndserver`), it would be very useful, we don't need to often start remotedev-server manually.

**Comment by zalmoxisus** [comment]
Maybe something like `--injectserver=reactnative` / `--injectserver=desktop`?

**Comment by jhen0409** [comment]
> Maybe something like --injectserver=reactnative / --injectserver=desktop?

I agreed. Will do it today. :)
