### ISSUE TITLE
Feature request: Ability to use as Express middleware

### ISSUE THREAD

**Issue by jenschelkopf** [zalmoxisus/remotedev-server#23]
Some deployment platforms hit specific endpoints to check the health of running web applications, and those endpoints are not configurable. For these systems remotedev-server will never be considered healthy because it only responds to specific endpoints.

To reproduce, run remotedev-server and curl an endpoint that is not defined. For example:

```
$ curl http://localhost:8000/health_check 
Cannot GET /health_check
```

While you could add a catch-all route that returns a 200 (and possibly the index page), adding the ability to use as an Express middleware would both solve this specific problem and also be very flexible for other use cases.

The [drakov](https://github.com/Aconex/drakov) project is an example of a web server that can be used independently or as middleware. Although I don't think remotedev-server needs the explicit init function, and a [classic](https://expressjs.com/en/guide/writing-middleware.html) middleware function should work.

Apologies for not submitting a PR with this request - my company doesn't let me open source code without approval.

**Comment by zalmoxisus** [comment]
Thanks, I'll look into it.

BTW, you can also start it in [a docker container](https://github.com/jhen0409/docker-remotedev-server) to be independent from your production app. Or just run `remotedev`. Including it directly inside express app is useful for development (as you don't have to run 2 commands), but doesn't seem to be the best practice for production apps.

**Comment by jenschelkopf** [comment]
Yeah, I saw the docker container. It doesn't help my use case though.

This request isn't about including remotedev-server inside of another app. It's about extending remotedev-server with additional behavior. Specifically extending it by adding a route that can respond appropriately about remotedev-server's health.

A couple of examples of systems that hit HTTP endpoints to check an application's health are [AWS](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html) and [Microsoft Awure](https://azure.microsoft.com/en-us/documentation/articles/load-balancer-get-started-internet-portal/#create-a-probe-lb-rule-and-nat-rules)

**Comment by zalmoxisus** [comment]
I see. It would be great to make it flexible in this way. However, the middleware approach doesn't fit the current architecture as our express instances run in workers, and are not in the same process as master. So, we can pass only serialized data from and to master.

Maybe @jondubois could point out to a solution on how we could pass express `app` to brokers and/or pass a callback to master like [here](https://github.com/Aconex/drakov#using-as-an-express-middleware).

**Comment by jenschelkopf** [comment]
Yeah, the more I looked at the code the more I realized this would require a hefty refactor.

After a bit more poking on my end I realized this isn't something I need for my particular deployment system. Feel free to close this as 'won't add'.

**Comment by zalmoxisus** [comment]
@jrullmann, if only health checking is necessary, we could just add parameters for a custom url and response (string) or just replace:

``` diff
-  app.get('/', function(req, res) {
+  app.get('*', function(req, res) {
    res.render('index', { port: worker.options.port });
  });
```

**Comment by jenschelkopf** [comment]
Yep, both of those would work

**Comment by zalmoxisus** [comment]
Then we'll use the latter. It's up in `0.2.1`.

Thanks for the suggestion. In case you need other customizations, let me know.

**Comment by jondubois** [comment]
@zalmoxisus It sounds like you figured it out, but yeah you can add a healthcheck on the workers - When the deployment system (or orchestrator) makes a request to that healthcheck route, the node.js cluster module will pass that request to a random worker.
