### ISSUE TITLE
Requests hang when exceptions are thrown

### ISSUE THREAD

**Issue by jenschelkopf** [zalmoxisus/remotedev-server#25]
Currently, if an exception occurs when communicating with the database the error is silently swallowed, and requests hang. This makes debugging very difficult 😀

Consider adding Promise rejection handling to the worker endpoints.

Here's an example of where the Promise fullfilled is handled, but not the Promise rejection:
https://github.com/zalmoxisus/remotedev-server/blob/master/lib/worker.js#L38

**Comment by zalmoxisus** [comment]
Added in #29. Thanks a lot for the investigation and pointing to the solution!
