### ISSUE TITLE
Provide API/Example to use to remotedev-server from other applications

### ISSUE THREAD

**Issue by peterpeter5** [zalmoxisus/remotedev-server#34]
If there would be a piece of documentation / an basic example, then other appliactions
and even other programming-languages could use this project. In concrete i try to integrate
my redux-python-port:
https://github.com/peterpeter5/pyredux
with this server. But i think it could be interesting for other people / applications.

**Comment by zalmoxisus** [comment]
PyRedux looks amazing!

I've just published [a docs draft](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md) with Python examples. Feel free to amend it. I used to be a fan of Django, but it was almost 10 years ago and already forgot everything.

**Comment by peterpeter5** [comment]
The docs look amazing! I will try to do the integration-work in the  next Days. Thank you for your  (well documented) reply on such short notice!

**Comment by peterpeter5** [comment]
The documentation is quite helpful, but i guess there is something wrong or left out. I am able to connect to the server, to "authenticate" as "master" and to send the INIT-Command (I can see the visualization). When i then send a lifted-STATE (sniffed by another application), then I am able to reproduce the logged state-tree (everything is visualized as expected). However, sending a request with:
```python 
data = {
    "type": "ACTION", 
    "payload": {
      "todos": "do some"
    },
    "action": {
      "timestamp": 1483349708506,
      "action": {
        "type": "ADD_TODO",
        "text": "hggg"
      }
    },
    "instanceId": "tAmA7H5fclyWhvizAAAi",
    "name": "LoggerInstance",
    "id": "tAmA7H5fclyWhvizAAAi"
  }
socket.emit("log", data)   # No difference when i use "log-noid"
```  
I could use the lifted-state, but than i would have to provide values like: ```isLocked``` and ```stagedActionIds``` which I am sure is not the best way to do

**Comment by zalmoxisus** [comment]
I just tried your snippet (on NodeJS) and I'm getting `ADD_TODO` action on http://remotedev.io/local/ (switching to local server in Settings):

```js
var scClient = require('socketcluster-client');
var socket = scClient.connect({ hostname: 'localhost', port: 8000 });
socket.connect();
socket.on('error', function(error) {
  console.error('Socket error', error);
});

socket.emit('login', 'master', function(error, channelName) {
  if (error) { console.log(error); return; }
  socket.subscribe(channelName);

  var data = {
    "type": "ACTION",
    "payload": {
      "todos": "do some"
    },
    "action": {
      "timestamp": 1483349708506,
      "action": {
        "type": "ADD_TODO",
        "text": "hggg"
      }
    },
    "instanceId": "tAmA7H5fclyWhvizAAAi",
    "name": "LoggerInstance",
    "id": "tAmA7H5fclyWhvizAAAi"
  };
  socket.emit("log", data);
});
```

**Comment by zalmoxisus** [comment]
Maybe `socketcluster-client-python` is not stringifying the object properly. You could try to add [`json.dumps`](https://docs.python.org/2/library/json.html):

```js
data = {
    "type": "ACTION",
    "payload": json.dumps({
      "todos": "do some"
    }),
    "action": json.dumps({
      "timestamp": 1483349708506,
      "action": {
        "type": "ADD_TODO",
        "text": "hggg"
      })
    },
    "instanceId": "tAmA7H5fclyWhvizAAAi",
    "name": "LoggerInstance",
    "id": "tAmA7H5fclyWhvizAAAi"
  };
```

**Comment by peterpeter5** [comment]
you were right about the socket-cluster-client   -   stringification, but in another way. When you pass in a string into the ```socket.emit``` - function (which i did, unlike my previous post...)  then this string gets ```json.dumps``` again. That was my problem. Now it works like charm. Thank you!
