### ISSUE TITLE
Broken on react-native 0.44

### ISSUE THREAD

**Issue by brunolemos** [zalmoxisus/remotedev-server#36]
After `injectserver`, the final `server.js` code end up like this:

`...`
```js
/* remotedev-server end */
 *
 * This source code is licensed under the BSD-style license found in the
```
`...`

Throwing the error `node_modules/react-native/local-cli/server/server.js: Unexpected token (10:1)`
```
   8 |       );
   9 | /* remotedev-server end */
> 10 |  *
```

**Comment by zalmoxisus** [comment]
Maybe @jhen0409 has any ideas of what is going on here?

**Comment by jhen0409** [comment]
Sorry for delay, I submitted https://github.com/zalmoxisus/remotedev-server/pull/38 for fix this. :)

**Comment by zalmoxisus** [comment]
It's up in `remotedev-server@0.2.2` and `remotedev-server@0.3.0-beta-4`.

Thanks a lot @jhen0409 for working on it!
