### ISSUE TITLE
[Proposal] Run remotedev-app on server

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remotedev-server#4]
Let it like http://remotedev.io, and in order not to use `webpack` on this, can we have a UMD bundle in remotedev-app repo?

If you think good, I'll send a PR. :)

**Comment by zalmoxisus** [comment]
Yes, an UMD bundle will be always useful, we may even include it via cdnjs in not webpack/browserify apps. Please do a pr. We may create it as [in remotedev](https://github.com/zalmoxisus/remotedev/blob/master/package.json#L13-L14).

As for adding `remotedev-app` here, it's not something I'd use for `remote-redux-devtools`, but can be included as a convenience for `remotedev`.

Another useful approach I think would be to include `remotedev-server' in`remotedev-app`:), so to extend electron app in`remotedev-app` to start server directly from there. So you will not have to care at all about the server part, just start the app and server runs in background. Close the app and the server stops.

**Comment by zalmoxisus** [comment]
Implemented in `v0.0.4`. Thanks for working on this!
