### ISSUE TITLE
How do I connect to my local remotedev-server on a real iOS device ?

### ISSUE THREAD

**Issue by hyperh** [zalmoxisus/remotedev-server#50]
On a real Android device you do `adb reverse tcp:8000 tcp:8000`. Is there something similar for iOS?

**Comment by akaztp** [comment]
Let me see if I understand correctly. You have an iOS app that should communicate with a remotedev-server instance, all on your local network (wifi or ethernet).
If this is the case, try to start the remotedev-server on host '0.0.0.0', disable local firewalls for the remotedev-server port and configure the iOS app to address your server local address (the ip or name in your LAN).

**Comment by hyperh** [comment]
@akaztp 

To be more specific:

Both iOS and my machine are on the same wifi network.

1. I'm hosting a web app on my local machine at `localhost:3000`.
1. I browse to `192.168.xx:3000` (address of my local machine on the LAN) on my iOS device
1. Not sure how to send Redux data back from iOS to my `remotedev-server`

I'll give your suggestions a shot though, thanks!

**Comment by akaztp** [comment]
I think you're missing a point between yours 1 and 2:
- host another webserver on my local machine (localhost:4000) with an instance of the remotedev-server.
Then, you connect to the remotedev-server using the same address but to port 4000

This new webserver can be started as stated in the "Usage" section of the README of this repo.

For example, on production I'm using:
- www.domain.com:80 for the web app
- report.domain.com:80 for the remotedev-server
