### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [zalmoxisus/remotedev-server#54]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by zalmoxisus** [comment]
Thanks for the suggestion and sorry about the late answer. EJS is not heavily used, just to include `remotedev-app`, but if you'd like to change it, I'm open to a PR (just make sure to do it against `0.3` branch).
