### ISSUE TITLE
uWS error, no pre-compiled binary available need a supported c++11 compiler

### ISSUE THREAD

**Issue by goleary** [zalmoxisus/remotedev-server#57]
I'm a bit at a loss, having installed multiple different c++ compilers and nuked my npm cache/node installation to no avail.  perhaps the uws version needs to be upgraded to a supported version?
running windows 10 node v8.11.2 remotedev-server 0.2.4
![image](https://user-images.githubusercontent.com/16123225/41056810-32d26bf8-697a-11e8-8ad8-725b42e98293.png)

**Comment by timc3** [comment]
I am getting the same but with the beta version. It's from socketcluster

Also problems install sqlite3, but sqlite4 installs no problem.

**Comment by timc3** [comment]
@goleary - I just found an ugly way around it. 

Somewhere install uws (hopefully the latest version builds for you), then move it.
```
npm install uws
mv node_modules/socketcluster-server/node_modules/uws node_modules/socketcluster-server/node_modules/uws-old
mv node_modules/uws node_modules/socketcluster-server/node_modules/
```

**Comment by michaellee8** [comment]
Just solved this problem using this one `npm install --global --production windows-build-tools`
source: https://github.com/SocketCluster/socketcluster/issues/298

**Comment by goleary** [comment]
@michaellee8 thanks, this solved my issue!  It still failed the first time I tried to run remotedev after installing the build-tools but on subsequent attempts it seems to be working correctly.

**Comment by 100ideas** [comment]
@timc3 Wow! Replaced`uws@8.14.0` with `uws@10.148.1` via your method and it worked! I had thought socketcluser-server would choke on breaking changes between the two versions but apparently not.

**Comment by timc3** [comment]
@michaellee8 I presume that is just for Windows?

**Comment by michaellee8** [comment]
@timc3 I guess that solution is just for windows since it install windows c++ build tools. However, on linux, you should check out if you've got proper c++ build tool likr g++ or clang and configured properly.

**Comment by erperejildo** [comment]
I get this error in Windows and Linux

**Comment by amyDoxy** [comment]
Try npm rebuild uws

**Comment by amyDoxy** [comment]
Try:
`npm rebuild uws`
