### ISSUE TITLE
Can not compile and installl uWS, change `wsEngine` to `ws` to solve this

### ISSUE THREAD

**Issue by s20208413** [zalmoxisus/remotedev-server#58]
Modify `index.js` like this:

```
> git diff
diff --git a/index.js b/index.js
index d9e5313..ba42ac2 100644
--- a/index.js
+++ b/index.js
@@ -35,6 +35,7 @@ module.exports = function(argv) {
           console.log('[RemoteDev] Start server...');
           console.log(repeat('-', 80) + '\n');
         }
+        options.wsEngine = 'ws';
         resolve(new SocketCluster(options));
       }
     });
```

After change that, it works well:

```
> remotedev --hostname=localhost --port=8000
[RemoteDev] Start server...
--------------------------------------------------------------------------------

   [Busy] Launching SocketCluster
   [Active] SocketCluster started
            Version: 6.8.0
            Environment: dev
            WebSocket engine: ws
            Port: 8000
            Master PID: 28389
            Worker count: 1
            Broker count: 1

```

**Comment by copslock** [comment]
hi,buddy,can you give some contact infomation that i saw you have made some fork code of the recowvery-applypatch.c which helps dumped out the boot.img by hex logcat to log file.
tencent qq weixin will be good

**Comment by s20208413** [comment]
@copslock  you can email me.

**Comment by tinkusam** [comment]
It will be good if we are getting one more option ```wsEngine``` to override to ```ws``` in order to resolve this issue.

**Comment by thromera** [comment]
Actively looking for a fix on that issue. Is a PR going to be open? :)

**Comment by tinkusam** [comment]
Excellent, now it works with the ```wsEngine``` option

`remotedev --wsEngine=ws --hostname=localhost --port=8082`

**Comment by zalmoxisus** [comment]
In `0.3.0` ws is used by default. For `uws` you have to specify `sc-uws` in `wsEngine`.
