### ISSUE TITLE
Security: update socketcluster dependency

### ISSUE THREAD

**Issue by ethanroday** [zalmoxisus/remotedev-server#64]
`socketcluster^8.0.0` is eventually dependent on `ws@3.1.0`, which has a [known security vulnerability](https://www.npmjs.com/advisories/550).

**Comment by ethanroday** [comment]
It's also eventually dependent on `hoek@2.16.3`, which is vulnerable to [prototype pollution](https://www.npmjs.com/advisories/566).

**Comment by donverduyn** [comment]
#65

**Comment by zalmoxisus** [comment]
Fixed in `0.3.0`.

**Comment by ethanroday** [comment]
Thanks!
